// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYG4ZbKD0KMazKIX5d8ZQuJOJ8OrKbcqU',
    appId: '1:406515815181:web:f47009cdae458070f7d644',
    messagingSenderId: '406515815181',
    projectId: 'myportfolio-8ae9b',
    authDomain: 'myportfolio-8ae9b.firebaseapp.com',
    storageBucket: 'myportfolio-8ae9b.firebasestorage.app',
    measurementId: 'G-10389B2FBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqrhFBZUInHl4m3qdZMxK_LHQd0atbZkA',
    appId: '1:406515815181:android:0f71dcac16b87707f7d644',
    messagingSenderId: '406515815181',
    projectId: 'myportfolio-8ae9b',
    storageBucket: 'myportfolio-8ae9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN5yNpXZ0U2is5jArksiALHqumI_TpoUY',
    appId: '1:406515815181:ios:e43675b0d27df9ccf7d644',
    messagingSenderId: '406515815181',
    projectId: 'myportfolio-8ae9b',
    storageBucket: 'myportfolio-8ae9b.firebasestorage.app',
    iosBundleId: 'com.example.flutterPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN5yNpXZ0U2is5jArksiALHqumI_TpoUY',
    appId: '1:406515815181:ios:c286c56276f78141f7d644',
    messagingSenderId: '406515815181',
    projectId: 'myportfolio-8ae9b',
    storageBucket: 'myportfolio-8ae9b.firebasestorage.app',
    iosBundleId: 'myportfolio.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYG4ZbKD0KMazKIX5d8ZQuJOJ8OrKbcqU',
    appId: '1:406515815181:web:be73ca12f6fc9ebef7d644',
    messagingSenderId: '406515815181',
    projectId: 'myportfolio-8ae9b',
    authDomain: 'myportfolio-8ae9b.firebaseapp.com',
    storageBucket: 'myportfolio-8ae9b.firebasestorage.app',
    measurementId: 'G-KSMG8ESBEY',
  );
}
